baseURL = "https://www.smartprog.xyz/"
languageCode = "ja-JA"
title = "10歳から初めるスマホプログラミング！"
theme="hugo-theme-learn"
baseurl = "https://www.smartprog.xyz/"
copyright = "© My Site"
canonifyurls = true

[params]
  description = "テストディスクリプション" #optional
  googleanalytics = "Your Tracking Id" # optional

# optional
[social]
  twitter = "Your Twitter Name"
  github = "Your Github Name"
  facebook = "Your facebook Name"
  gplus = "Your Google+ profile name"
  linkedin = "Your LinkedIn Name"

  # For search functionnality
 [outputs]
 home = [ "HTML", "RSS", "JSON"]
